site_name: love_xyz documentation
site_url: https://Zellicious.github.io/love_xyz/

theme:
  name: material
  
nav:
  - Home: index.md
  - Navigation: doc-main.md
  - Documentation: 
    - engine.lua: engine.md
