site_name: love_xyz documentation
site_url: https://Zellicious.github.io/lovexyz-docs/

theme:
  name: material
  logo: png/icon.svg
  favicon: png/icon.svg
  palette:
    scheme: slate
    primary: black
  
  
nav:
  - Home: index.md
  - Navigation: doc-main.md
  - Documentation: 
    - engine.lua: scripts/engine.md
    - obj.lua: scripts/obj.md
    - triangles.lua: scripts/triangles.md
